### ISSUE TITLE
how about 5000 alphabet?

### ISSUE THREAD

**Issue by Aurora11111** [wulivicte/crnn#13]

**Comment by YoungMiao** [comment]
@Aurora11111 I have trained 4,000 commonly used Chinese characters. it's ok, is it a problem with the amount of data set? I used about 30 million pictures.

**Comment by Aurora11111** [comment]
@YoungMiao 你用了3000万张图片吗？每张图片有多少个字呢

**Comment by Aurora11111** [comment]
@YoungMiao 我目前用的５００万张图片，训练速度好慢，快一周了，ｌｏｓｓ已经收敛到1.3了，还在继续下降，但是很慢.不知道你当时训练了多久？

**Comment by Hubert2102** [comment]
hello，加个微信或者QQ联系吧？872904258 @Aurora11111
