### ISSUE TITLE
训练模型保存在哪儿呢

### ISSUE THREAD

**Issue by liuyiyiyiyi** [wulivicte/crnn#14]
你好，我没有找到保存训练模型的代码，也不知道训练好的模型时保存在哪儿

**Comment by YoungMiao** [comment]
@liuyiyiyiyi  --experiment        模型保存目录

**Comment by liuyiyiyiyi** [comment]
嗯嗯我已经知道了，我想请问一下训练中文的时候，在训练模型中的alphabet是不是得包含你样本中所有的中文字，中文字有上千个，常见的也有3000个，这样的话alphabet是不是得把这几千个中文字都列出来？

**Comment by liuyiyiyiyi** [comment]
嗯嗯我已经知道了，我想请问一下训练中文的时候，在训练模型中的alphabet是不是得包含你样本中所有的中文字，中文字有上千个，常见的也有3000个，这样的话alphabet是不是得把这几千个中文字都列出来？

**Comment by liuyiyiyiyi** [comment]
嗯嗯我已经知道了，我想请问一下训练中文的时候，在训练模型中的alphabet是不是得包含你样本中所有的中文字，中文字有上千个，常见的也有3000个，这样的话alphabet是不是得把这几千个中文字都列出来？
