### ISSUE TITLE
there are two bugs in the code

### ISSUE THREAD

**Issue by bianlongpeng** [wulivicte/crnn#15]
first :
preds = preds.squeeze(2)    ->    preds = preds.squeeze(1)
second:
preds = preds.transpose(1, 0).contiguous().view(-1)   ->  preds = preds.transpose(-1, 0).contiguous().view(-1)
to change the two lines then get the result

**Comment by YoungMiao** [comment]
@bianlongpeng I tried it, no problem.

**Comment by NK-Hubert** [comment]
你好，可以加一下QQ或微信么，最近也正在做汉字的OCR，想交流一下，872904258

**Comment by bianlongpeng** [comment]
@YoungMiao when I run the code ("crnn_main.py") to  train chinese words , the error list:
![default](https://user-images.githubusercontent.com/22487109/45809956-1aab1400-bcfc-11e8-9499-7b10daaa3671.png)
but when I changed :  preds = preds.squeeze(2) -> preds = preds.squeeze(1), this error was  solved
,it is same to the second bug. 
why is it？

**Comment by Dinghow** [comment]
I got the same problem too.
