### ISSUE TITLE
精确度为0，验证集没输出

### ISSUE THREAD

**Issue by Hubert2102** [wulivicte/crnn#16]
你好，我自己用您给的生成数据工程synthdata-zh做数据集，其中word.txt是26个小写字母，每个字母生成550训练样本，50的验证样本，共600张。
然后在CRNN工程里的tool里面，用tolmdb.py产生相关训练与验证集合文件，再把key.py里面的alphabet也改成26个小写字母，开始训练，但是出现这样的结果，不知道哪里有问题？
<img width="221" alt="_20180920154344" src="https://user-images.githubusercontent.com/29619323/45803392-1840be00-bcec-11e8-8246-4df95dbe75cc.png">

**Comment by YoungMiao** [comment]
@NK-Hubert 你是使用的pytorch0.4？

**Comment by Hubert2102** [comment]
0.3

**Comment by Hubert2102** [comment]
训练了一段时间吧，有输出了，但是验证集的输出结果都是一样的
<img width="213" alt="_20180920165317" src="https://user-images.githubusercontent.com/29619323/45807266-b5542480-bcf5-11e8-82fd-b851b0913ea6.png">

**Comment by Aurora11111** [comment]
@NK-Hubert 是不是你的学习率设置的太大

**Comment by YoungMiao** [comment]
@NK-Hubert 更换优化方法，比如Adam

**Comment by Hubert2102** [comment]
这是我的命令参数设置,（1）26个小写字母会产生26x550的训练集合，26x50的验证集合（2）nh为128，好像按照readme里面的“训练和预测采用的类别数和LSTM隐藏层数需保持一致”设置为26+1的话，会报错维数不对，（3）预训练模型是您提供的那个netCRNN_ch_nc_21_nh_128.pth，（4）--experiment expr/ 设置了但是那个文件夹始终为空，不知道为啥没保存呢（5）学习率我设置的是0.005 @Aurora11111 
<img width="877" alt="_20180920170932" src="https://user-images.githubusercontent.com/29619323/45808259-f9482900-bcf7-11e8-8457-060b5a9f8075.png">
OK，我试试ADAM @YoungMiao

**Comment by Aurora11111** [comment]
@NK-Hubert 你的ｓａｖｅInter设置小一点就回显示了５００　明显大于２２４了，当然不会输出．　学习率可以尝试一下０．００００５

**Comment by Hubert2102** [comment]
<img width="219" alt="_20180920174348" src="https://user-images.githubusercontent.com/29619323/45810256-ce140880-bcfc-11e8-9d96-7c231d632230.png">
perfect！Adam设置了之后果然很快就会出现验证集字母输出了！
学习率调小之后，识别结果也很快就到96%多了，还有格外感谢兄弟 @Aurora11111 ，最近刚接触OCR，做汉字识别，环境配置和安装遇到了好多坑，在各个GitHub的issue上都有看到你，神奇的是我遇到的很多问题你都有问过，找到了解决方案哈哈哈哈

**Comment by Aurora11111** [comment]
@NK-Hubert 我也是刚接触OCR,有问题一起交流
