### ISSUE TITLE
ncalss

### ISSUE THREAD

**Issue by liuyiyiyiyi** [wulivicte/crnn#19]
我使用中文字符时，一个字符的len是3,当我使用100时，len为300，nclass为301，但是我看你使用了中文字符，类别数就是比字符数多1，所以我觉得有些疑问。还有一个问题就是我用合成的样本进行训练和测试，效果比较好，但是我用自然场景下扣出来的文本进行测试，如果只是效果不好那我觉得是合理的，但是我预测出来的标签序列有alphabet中不包含的字符，这让我觉得很奇怪。请问你有遇到过这个问题吗，或者你的看法是什么呢？

**Comment by YoungMiao** [comment]
@liuyiyiyiyi 没有碰到过识别出标签序列中不包含的字符
