### ISSUE TITLE
输入图片尺寸

### ISSUE THREAD

**Issue by liuyiyiyiyi** [wulivicte/crnn#21]
你的输入图片尺寸高度为32，宽度时根据高度缩放的，是在脚本中将keep ratio设置为true吗

**Comment by liuyiyiyiyi** [comment]
而且我看你的测试代码中将测试的图片都resize到了100×32，root=opt.valroot, transform=dataset.resizeNormalize((100, 32)))，但是你说输入图片又是高度为32，宽度按比率缩放，这两个不是不统一吗，训练和测试的处理方法不一致，训练时字符不会北拉伸，而测试时字符被拉伸，这样是否有问题呢？

**Comment by YoungMiao** [comment]
@liuyiyiyiyi 测试拉伸影响不大
