### ISSUE TITLE
请问下你的训练样本是怎样的？

### ISSUE THREAD

**Issue by DLUTfangping** [wulivicte/crnn#7]
例如对于alphabet = 'ACIMRey万下依口哺摄次状璐癌草血运重' 的训练样本，是一个字一个字作为训练样本吗？还是词组性的，例如哺璐草？

**Comment by YoungMiao** [comment]
@DLUTfangping 是单字和词组的，生成样本的可参考我的另外的project，https://github.com/YoungMiao/synthdata-zh

**Comment by liangshuang1993** [comment]
@YoungMiao 你好，我是用的自己生成的数据集进行了训练，训练集包含中文，英文，数字，共370个左右，总共几百万张。

最终训练集Loss: 1.518994。验证集Test loss: 2.194840, accuray: 0.523750。

想问下几个问题，非常感谢！
1. 训练集没有足够收敛，我已经试过不同的learning rate，时间也够长了，但是效果还不好，请问下有什么训练技巧吗？
2. 在验证集上已经过拟合了，但我感觉我的训练集也不小了，是否是我的训练集太过于单一了？我之前有想过是不是我用的字体种类与背景图片太少了，但是我看你上面提供的project里面也不多。想请问下会是什么问题呢？
3. 我实际环境中的要测试的图片都是黑白的。是否我在处理前都应该二值化一下？

非常感谢！！

**Comment by Aurora11111** [comment]
@liangshuang1993 hello,请问你训练出来了没有，最终使用了多少长图片，每张多少个字

**Comment by Pro-flynn** [comment]
> @YoungMiao 你好，我是用的自己生成的数据集进行了训练，训练集包含中文，英文，数字，共370个左右，总共几百万张。
> 最终训练集Loss: 1.518994。验证集Test loss: 2.194840, accuray: 0.523750。
> 想问下几个问题，非常感谢！
> 
> 训练集没有足够收敛，我已经试过不同的learning rate，时间也够长了，但是效果还不好，请问下有什么训练技巧吗？
> 在验证集上已经过拟合了，但我感觉我的训练集也不小了，是否是我的训练集太过于单一了？我之前有想过是不是我用的字体种类与背景图片太少了，但是我看你上面提供的project里面也不多。想请问下会是什么问题呢？
> 我实际环境中的要测试的图片都是黑白的。是否我在处理前都应该二值化一下？
> 
> 非常感谢！！


你好 方便得话 我能参考一下 你生成数据集的project吗

**Comment by Aurora11111** [comment]
@Pro-xiaowen you can reference：
https://github.com/Aurora11111/TextRecognitionDataGenerator
